root = "."
tmp_dir = "tmp"

[build]
# 只需要编译 main 包
cmd = "go build -o ./tmp/main ."
# 二进制文件路径
bin = "tmp/main"
# 监控的文件扩展名
include_ext = ["go", "tpl", "tmpl", "html", "json"]
# 忽略这些文件夹
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
# 忽略这些文件
exclude_file = []
# 发生错误时停止运行
stop_on_error = true
# 日志格式
log = "air_errors.log"

[log]
# 显示日志时间
time = true

[color]
# 自定义每个部分显示的颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 退出时是否删除tmp目录
clean_on_exit = true 